#!/bin/bash

find . -maxdepth 1 -mindepth 1 -type d | while read i
do
    if [ -r "$i/.note" ]; then
        echo "$i:"
        sed 's/^/    /' "$i/.note"
        echo ""
    fi
done

while [ $(pwd -P) != "/" ]; do
    if [ -r ".note" ]; then
        echo "My note @$(pwd -P):"
        sed 's/^/    /' ".note"
        echo ""
        break
    fi
    cd ..
done
