#!/bin/bash

echo "Import $1 to octopress based on $OCTOPRESSDIR ..."

TARGETBASEDIR=$OCTOPRESSDIR/source/images

if [ ! -d "$TARGETBASEDIR" ]; then
    echo "Error: based directory is not present, expected: $TARGETBASEDIR"
    exit 255
fi

TARGETDIR=$TARGETBASEDIR/blogimage

# Create target dir if it is not present
mkdir -p "$TARGETDIR"
if [ $? -ne 0 ]; then
    echo "Error: cannot create target dir"
    exit 255
fi


# Process image.

for f in "$@"; do
    if [ ! -r "$f" ]; then
        echo "Error: unable to get $f."
        exit 255
    fi

    # Get md5 of image.
    MD5SUM=$(md5 -q "$f")
    # echo "MD5: $MD5SUM"

    # Get target name.
    TARGETBASENAME=$(echo ${f%.*} | sed -e 's/ /-/g')
    TARGETNAME=$TARGETBASENAME-$MD5SUM.jpg
    # echo "Target file name is: $TARGETNAME"

    # Convert to target.
    echo "Converting image..."
    convert "$f" -resize 1000x1000\> $TARGETDIR/$TARGETNAME
    if [ $? -ne 0 ]; then
        echo "Error: convert source image to target image"
        exit 255
    fi

    # Print target url.
    echo "Target url:" /images/blogimage/$TARGETNAME
done
